### ISSUE TITLE
need help  starting project

### ISSUE THREAD

**Issue by zirconias** [MatthewVita/spring-boot-private-chat#3]
hi there,  
i browsed github for nice project with spring boot stack, i found your repo.

it seems interesting , but i think you can work out the readme and provide some guides to start the project.

i'm stack with an exception when trying to inject a redis bean.

**Comment by MatthewVita** [comment]
Hi!

Do you have redis installed? If so, what is the version and port it's running on?

Thanks,
Matthew

**Comment by zirconias** [comment]
this is the issue :p i didn't check the pom for dependencies,  i'll start a redis docker container and see if it builds

**Comment by MatthewVita** [comment]
I just listed the dependencies generically here: https://github.com/MatthewVita/spring-boot-private-chat#setup

I would put the `apt-get` installs in there, but not everyone uses Linux :(
